### ISSUE TITLE
--output-encoding parameter is not used

### ISSUE THREAD

**Issue by novalis** [twitter/libwatchman#20]
libwatchman now seems to default to bser encoding, but --output-encoding (and --server-encoding?) are not passed to watchman.  This means that watchman will write JSON but libwatchman will be expecting bser.

Also libwatchman could maybe detect json vs bser by looking at the 1st byte of server output, which will be either '{' or '\x01'?

**Comment by mcguigan** [comment]
According to this page (https://facebook.github.io/watchman/docs/socket-interface.html) watchman will respond with the encoding used in making the request.

**Comment by novalis** [comment]
That's the socket interface, not the command-line interface (which libwatchman uses to get the socket name).

**Comment by novalis** [comment]
To be clear: this means that libwatchman isn't working for me out of the box.  I get: "Got bad JSON/BSER from watchman get-sockname: object expected".  Is it working for you?

**Comment by mcguigan** [comment]
Yeah, it is working for me, but I just realized I don't have that bser code integrated into 2.8 -- so I'll have to merge that and try it out.

**Comment by novalis** [comment]
A minimal fix is: https://github.com/novalis/libwatchman/commit/7343e5b9848fef793ec3434a9cceaad81b2a3051
